language: python
jobs:
  include:
    - name: "Python 3.7"
      python: 3.7
      before_install:
        - make setup
    - name: "Python 3.6"
      python: 3.6
      before_install:
        - pip install -U .[all]
        - pip install codecov
install: pip freeze
script:
  - make lint
  - coverage run -m pytest tests/flytekit/unit
  - shellcheck **/*.sh
after_success:
  - codecov
